/**
 * Export-artifact generators. These turn a set of forged tokens into
 * ready-to-run commands the user executes from their OWN authorized
 * environment. The web app never sends requests itself.
 */

export interface ArtifactConfig {
  /** Target URL, e.g. https://target.example/api/me */
  targetUrl: string;
  /** Header name carrying the token, e.g. Authorization */
  headerName: string;
  /** Prefix before the token, e.g. "Bearer " */
  headerPrefix: string;
  /** HTTP method */
  method: string;
}

export const DEFAULT_ARTIFACT_CONFIG: ArtifactConfig = {
  targetUrl: "https://TARGET.example/api/me",
  headerName: "Authorization",
  headerPrefix: "Bearer ",
  method: "GET",
};

function headerValue(cfg: ArtifactConfig, token: string): string {
  return `${cfg.headerPrefix}${token}`;
}

export function toCurl(cfg: ArtifactConfig, tokens: string[]): string {
  return tokens
    .map(
      (t, i) =>
        `# token ${i + 1}\n` +
        `curl -sS -X ${cfg.method} '${cfg.targetUrl}' \\\n` +
        `  -H '${cfg.headerName}: ${headerValue(cfg, t)}'`,
    )
    .join("\n\n");
}

export function toHttpFile(cfg: ArtifactConfig, tokens: string[]): string {
  // VS Code REST Client / IntelliJ .http format. `###` separates requests.
  return tokens
    .map(
      (t, i) =>
        `### token ${i + 1}\n` +
        `${cfg.method} ${cfg.targetUrl}\n` +
        `${cfg.headerName}: ${headerValue(cfg, t)}\n`,
    )
    .join("\n");
}

export function toBurpIntruder(tokens: string[]): string {
  // Bare tokens, one per line — paste into Intruder's payload list.
  return tokens.join("\n");
}

export function toJwtTool(cfg: ArtifactConfig, token: string): string {
  // Representative jwt_tool invocation for the first token.
  return (
    `# Inspect / scan with jwt_tool (https://github.com/ticarpi/jwt_tool)\n` +
    `python3 jwt_tool.py '${token}'\n\n` +
    `# Run the active exploit playbook against the live endpoint:\n` +
    `python3 jwt_tool.py -t '${cfg.targetUrl}' \\\n` +
    `  -rh '${cfg.headerName}: ${cfg.headerPrefix}${token}' -M at`
  );
}

export function toNucleiTemplate(cfg: ArtifactConfig, tokens: string[]): string {
  const payloadLines = tokens
    .map((t) => `          - "${cfg.headerPrefix}${t}"`)
    .join("\n");
  return `id: jwt-forged-token-acceptance

info:
  name: Forged JWT acceptance check
  author: jwtforge
  severity: high
  description: >
    Sends forged JWT variants generated by jwtforge.com and flags any that the
    server accepts (HTTP 200). Review matches manually — a 200 is a signal, not
    proof. Only run against systems you are authorized to test.
  tags: jwt,auth,fuzz

http:
  - raw:
      - |
        ${cfg.method} {{Path}} HTTP/1.1
        Host: {{Hostname}}
        ${cfg.headerName}: §token§

    payloads:
      token:
${payloadLines}

    attack: batteringram
    stop-at-first-match: false

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
# NOTE: tune the matcher to your target — a 200 may not mean auth succeeded.
# Set the target with: nuclei -u ${cfg.targetUrl} -t this-template.yaml
`;
}

export interface ArtifactBundle {
  curl: string;
  http: string;
  burp: string;
  nuclei: string;
  jwtTool: string;
}

export function buildArtifacts(
  cfg: ArtifactConfig,
  tokens: string[],
): ArtifactBundle {
  return {
    curl: toCurl(cfg, tokens),
    http: toHttpFile(cfg, tokens),
    burp: toBurpIntruder(tokens),
    nuclei: toNucleiTemplate(cfg, tokens),
    jwtTool: tokens.length > 0 ? toJwtTool(cfg, tokens[0]) : "",
  };
}
